// Copyright (c) TrueTickets, Inc.
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// IssuerModel describes the Terraform schema for a Google Wallet Issuer.
// Note: issuer_id is stored as string in Terraform to avoid int64 overflow issues.
type IssuerModel struct {
	// ID is the unique identifier for the issuer (read-only, auto-generated by API).
	// Stored as string to avoid JavaScript/HCL int64 precision issues.
	ID types.String `tfsdk:"id"`

	// Name is the account name of the issuer.
	Name types.String `tfsdk:"name"`

	// HomepageURL is the URL for the issuer's home page.
	HomepageURL types.String `tfsdk:"homepage_url"`

	// ContactInfo contains the issuer's contact information.
	ContactInfo types.Object `tfsdk:"contact_info"`
}

// IssuerContactInfoModel describes the contact information for an issuer.
type IssuerContactInfoModel struct {
	// Name is the primary contact name.
	Name types.String `tfsdk:"name"`

	// Phone is the primary contact phone number.
	Phone types.String `tfsdk:"phone"`

	// Email is the primary contact email address.
	Email types.String `tfsdk:"email"`

	// AlertsEmails is a list of email addresses that receive alerts.
	AlertsEmails types.List `tfsdk:"alerts_emails"`
}

// IssuersDataSourceModel describes the data source for listing issuers.
type IssuersDataSourceModel struct {
	// Issuers is the list of issuers.
	Issuers []IssuerModel `tfsdk:"issuers"`
}

// PermissionsModel describes the Terraform schema for Google Wallet Permissions.
// This resource is authoritative - it manages all permissions for an issuer.
type PermissionsModel struct {
	// IssuerID is the ID of the issuer these permissions belong to.
	// Stored as string to avoid int64 precision issues.
	IssuerID types.String `tfsdk:"issuer_id"`

	// Permissions is the complete list of permissions for this issuer.
	Permissions []PermissionModel `tfsdk:"permissions"`
}

// PermissionModel describes a single permission entry.
type PermissionModel struct {
	// EmailAddress is the email of the user, group, or service account.
	EmailAddress types.String `tfsdk:"email_address"`

	// Role is the role granted (OWNER, READER, or WRITER).
	Role types.String `tfsdk:"role"`
}
